### PR TITLE
[tests] Add fixture with nullable param

### LINKED ISSUE #39: NarrowPublicClassMethodParamTypeRule: conflicts with explicitly nullable types in PHP 8.4
PHP 8.4 deprecates implicitly nullable types:
https://wiki.php.net/rfc/deprecate-implicitly-nullable-types

Which means to set a default value we have to explicitly allow `null` or `?type`:

```php
public function foo(?bool $dryRun = true) {}
```

Which could lead to this error:

```
Parameters should have "bool" types as the only types passed to this method
```

### PR DESCRIPTION
**Pull request by TomasVotruba**
Surpasses https://github.com/rectorphp/type-perfect/pull/56

Closes https://github.com/rectorphp/type-perfect/issues/39

### CODE REVIEW

File: tests/Rules/NarrowPublicClassMethodParamTypeRule/Fixture/ExplicitlyNullableParams.php [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+        ?bool $bool = true,
+    ): bool
+    {
+        return $bool;
+    }
+
+    static public function run(): void
+    {
+        $skipDateTimeMix = new ExplicitlyNullableParams();
+        $skipDateTimeMix->test(false);
```
Comment (TomasVotruba) [inline tests/Rules/NarrowPublicClassMethodParamTypeRule/Fixture/ExplicitlyNullableParams.php:19]: This is actually expected, as only `bool` value is passed. Never `null`

If `null` is passed as well, there is no error :+1:
